/*
    goal: compare ss_mem from c code to ss from verilog
    step:
        1. use readmemh to load hex value from
            input: ck_mem,sk_mem
            output: ss_mem
        generated by official c code
        readmemh loads a memory -> 8 bits per entry
        2. load 
            ct_mem -> decryption_top's ct
            sk_mem -> decryption_top's sk
            ss_mem -> expected_ss to compare with decryption_top's ss
        3. see if decryption_top's ss match with expected_ss
        4. it fails, f = 0.
            that means ct_prime != ct
            the reencrypted message didn't match the original
            4.1 check if m_prime from c code = m_prime in verilog
                if not equal, bug is before post_decryption 
                result: m_prime is equal, the bug is in post decryption
            4.2 check (c',pre−k') = SHA3−512(pre−k,m')
            and Ct'=IND−CPA−KyberEncryption (m',PK,c')
                see if c',pre−k', Ct'
                result: c' and pre-k' match, ct' doesn't
                this means the bug is in re-encryption
            4.4 check PK into re-encryption
                result: PK matches C, the problem is in re-encryption
            4.5 check msg_poly in pre_encryption (4. Decode decompress msg) in encryption_top
                result: normal
            4.6 check r,e1,e2 to check noise generation in pre_encryption(7. Noise Generation)
                result: matches with C result
                now we must test 
                1. decode_pk -> t_vec / rho
                2. public_matrix_gen -> A^T
                3. main_computation -> x/y
                4. add/reduce/compress
*/
`timescale 1ns / 1ps
import params_pkg::*;
module decryption_top_tb;
    localparam int SK_WIDTH = (KYBER_N * KYBER_RQ_WIDTH * KYBER_K) +
                          (KYBER_N * KYBER_RQ_WIDTH * KYBER_K) + KYBER_N +
                          (2 * KYBER_N);
    logic clk,rst,start;
    logic [8703:0] ct;
    logic [SK_WIDTH-1:0] sk;
    reg f;
    logic [KYBER_N-1:0] ss;
    reg decrypt_done;
    
    decryption_top dut(
        .clk(clk),
        .rst(rst),
        .start(start),
        .ct(ct),
        .sk(sk),
        .f(f),
        .ss(ss),
        .decrypt_done(decrypt_done)
    );

    logic [7:0] ct_mem [0:1087];
    logic [7:0] sk_mem [0:2399];
    logic [7:0] ss_mem [0:31];
    logic [7:0] m_mem [0:31];
    logic [7:0] pre_k_prime_mem [0:31];
    logic [7:0] c_prime_mem [0:31];
    logic [7:0] ct_prime_mem [0:1087];
    logic [7:0] pk_mem [0:1183];

    logic [9471:0] expected_pk;
    logic [255:0] expected_m;
    logic [255:0] expected_pre_k_prime;
    logic [255:0] expected_c_prime;
    logic [8703:0] expected_ct_prime;
    logic [255:0] expected_ss;
    always #5 clk = ~clk;
    
    initial begin
        clk = 0;
        rst = 1;
        start = 0;
        ct = '0;
        sk = '0;
        expected_ss = '0;
        expected_m = '0;
        expected_pre_k_prime = '0;
        expected_c_prime = '0;
        expected_ct_prime = '0;

        $readmemh("C:/Users/Tony/kyber/kyber768-accelerator-on-fpga/experimental/tony/decryption_top_testcase/ct.mem", ct_mem);
        $readmemh("C:/Users/Tony/kyber/kyber768-accelerator-on-fpga/experimental/tony/decryption_top_testcase/sk.mem", sk_mem);
        $readmemh("C:/Users/Tony/kyber/kyber768-accelerator-on-fpga/experimental/tony/decryption_top_testcase/ss_expected.mem", ss_mem);
        $readmemh("C:/Users/Tony/kyber/kyber768-accelerator-on-fpga/experimental/tony/decryption_top_testcase/m_expected.mem", m_mem);
        $readmemh("C:/Users/Tony/kyber/kyber768-accelerator-on-fpga/experimental/tony/decryption_top_testcase/pre_k_prime_expected.mem", pre_k_prime_mem);
        $readmemh("C:/Users/Tony/kyber/kyber768-accelerator-on-fpga/experimental/tony/decryption_top_testcase/c_prime_expected.mem", c_prime_mem);
        $readmemh("C:/Users/Tony/kyber/kyber768-accelerator-on-fpga/experimental/tony/decryption_top_testcase/ct_prime_expected.mem", ct_prime_mem);
        $readmemh("C:/Users/Tony/kyber/kyber768-accelerator-on-fpga/experimental/tony/decryption_top_testcase/pk.mem", pk_mem);

        for (int i = 0; i < 1184; i++)
            expected_pk[8*i +: 8] = pk_mem[i];

        for (int i = 0; i < 32; i++)
            expected_pre_k_prime[8*i +: 8] = pre_k_prime_mem[i];

        for (int i = 0; i < 32; i++)
            expected_c_prime[8*i +: 8] = c_prime_mem[i];

        for (int i = 0; i < 1088; i++)
            expected_ct_prime[8*i +: 8] = ct_prime_mem[i];
    
        for (int i = 0; i < 32; i++)
            expected_m[8*i +: 8] = m_mem[i];

        for (int i = 0; i < 1088; i++)
            ct[8*i +: 8] = ct_mem[i];

        for (int i = 0; i < 2400; i++)
            sk[8*i +: 8] = sk_mem[i];

        for (int i = 0; i < 32; i++)
            expected_ss[8*i +: 8] = ss_mem[i];
        repeat (5) @(posedge clk);
        rst = 0;

        repeat (2) @(posedge clk);
        start = 1;
        @(posedge clk);
        start = 0;

        wait (decrypt_done);
        for (int i = 0; i < 8; i++) begin
            $display("reencrypt t_vec[0][%0d] = %0d",
                i,
                dut.post_decryption_uut.encrypt_post_dec.t_vec[0][12*i +: 12]
            );
        end

        $display("reencrypt rho = %h",
            dut.post_decryption_uut.encrypt_post_dec.pre_encryption_uut.rho
        );
        /*
        for (int i = 0; i < 8; i++) begin
            $display("reencrypt msg_poly[%0d] = %0d",
                i,
                dut.post_decryption_uut.encrypt_post_dec.msg_poly[i]
            );
        end

        for (int i = 0; i < 8; i++) begin
            $display("reencrypt r[0][%0d] = %0d",
                i,
                dut.post_decryption_uut.encrypt_post_dec.r[0][i]
            );
        end

        for (int i = 0; i < 8; i++) begin
            $display("reencrypt e1[0][%0d] = %0d",
                i,
                dut.post_decryption_uut.encrypt_post_dec.e1[0][i]
            );
        end

        for (int i = 0; i < 8; i++) begin
            $display("reencrypt e2[%0d] = %0d",
                i,
                dut.post_decryption_uut.encrypt_post_dec.e2[i]
            );
        end
        */
        /*
        for (int i = 0; i < 16; i++) begin
            $display("PK byte[%0d]: got=%02h expected=%02h",
                i,
                dut.PK[8*i +: 8],
                expected_pk[8*i +: 8]
            );
        end
        for (int i = 0; i < 16; i++) begin
            $display("reencrypt PK byte[%0d]: got=%02h expected=%02h",
                i,
                dut.post_decryption_uut.encrypt_post_dec.encryption_key[8*i +: 8],
                expected_pk[8*i +: 8]
            );
        end
        
        for (int i = 0; i < 16; i++) begin
            $display("ct_prime byte[%0d]: got=%02h expected=%02h original=%02h",
                i,
                dut.post_decryption_uut.ct_prime[8*i +: 8],
                expected_ct_prime[8*i +: 8],
                ct[8*i +: 8]
            );
        end*/

        $display("got      m = %h", dut.m);
        $display("expected m = %h", expected_m);

        $display("got      pre_k' = %h", dut.post_decryption_uut.pre_k_prime);
        $display("expected pre_k' = %h", expected_pre_k_prime);

        $display("got      c' = %h", dut.post_decryption_uut.c_prime);
        $display("expected c' = %h", expected_c_prime);
        
        $display("got      ct' = %h", dut.post_decryption_uut.ct_prime);
        $display("expected ct' = %h", expected_ct_prime);

        $display("got      ss = %h", ss);
        $display("expected ss = %h", expected_ss);
        $display("f = %b", f);
        $display("m = %h", dut.m);
        $display("pre_k = %h", dut.pre_k);
        $display("coin = %h", dut.coin);
        $display("ct original  = %h", ct);

        if (ss === expected_ss)
            $display("PASS: decryption_top matches C reference");
        else
            $fatal(1, "FAIL: decryption_top mismatch");

        $finish;
    end;
endmodule